GymManagementPL/Controllers/MemberController.cs
using GymManagmentBLL.Services.Interfaces;
using GymManagmentBLL.ViewModels.MemberViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GymManagementPL.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMemberService memberService1; 
        public MemberController(IMemberService memberService )
        {
            memberService1 = memberService; 
        }

         #region GetAllmembers 
        public ActionResult Index()
        {
          var members =  memberService1.GetAllMembers(); 

            return View(members);

        }
        #endregion



         #region  GetMemberData



        public ActionResult MemberDetails(int id)

        {

            if (id <= 0)

            {
                TempData["ErrorMessage"] = "Id of member is not zero or Nigative"; 
                return RedirectToAction(nameof(Index)); 
            }

            var member = memberService1.GetMemberDetails(id); 
            if (member == null )
            {
                TempData["ErrorMessage"] = "Member Not found ";
                return RedirectToAction(nameof(Index)); 
            }

            return View(member); 


        }




        #endregion




        #region HealthrecordDtails

        public ActionResult Healshrecorddetails (int id )
        {
            if (id <= 0)

            {
                TempData["Error message "] = "Id of Healthrecord is not zero or Nigative";

                return RedirectToAction(nameof(Index));
            }

            var Healthrecord = memberService1.GetMemberHealthRecordDetails(id);

            if (Healthrecord == null)
            {
                TempData["Error message "] = "Healthrecord Not found ";
                return RedirectToAction(nameof(Index));
            }

            return View(Healthrecord);




        }

        #endregion




        #region Add Member 


        public ActionResult Create()
        {
            return View(); 
        }

        [HttpPost]
        public ActionResult CreateMember ( CreateMemberViewModel createMember)
        {

            if(!ModelState.IsValid)
            {

                ModelState.AddModelError("DataInvalid", "Check data and missing fields");

                return View(nameof(Create), createMember); 
            }

            bool result = memberService1.CreateMember(createMember); 

            if (result)
            {
                TempData["SuccessMessage"] = "Member Created Successfully";

            }
            else
            {

                TempData["ErrorMessage"] = "Add member Failed";
            }


            return RedirectToAction(nameof(Index)); 





        }

        #endregion





        #region UpdateMember 


        public ActionResult MemberEdit(int id)
        {


            if (id <= 0)

            {
                TempData["ErrorMessage"] = "Id of member is not zero or Nigative";
                return RedirectToAction(nameof(Index));
            }


            var Member = memberService1.GetMemberToUpdate(id); 
            if(Member == null)
            {
                TempData["ErrorMessage"] = "Member Not found ";
                return RedirectToAction(nameof(Index));
            }

            return View(Member); 


        }


        [HttpPost]
        public ActionResult MemberEdit ([FromRoute] int id , MemberToUpdateViewModel memberToUpdate)
        {


            if (!ModelState.IsValid)
                return View(memberToUpdate);


            var result = memberService1.UpdateMmeberDetails(id, memberToUpdate);


            if (result)
            {
                TempData["SuccessMessage"] = "Member Updated Successfully";

            }
            else
            {

                TempData["ErrorMessage"] = "Update member Failed";
            }


            return RedirectToAction(nameof(Index));



        }





        #endregion




        #region DeleteMember



        public ActionResult Delete (int id )
        {

            if (id <= 0)

            {
                TempData["ErrorMessage"] = "Id of member is not zero or Nigative";
                return RedirectToAction(nameof(Index));
            }


            var Member = memberService1.GetMemberDetails(id);
            if (Member == null)
            {
                TempData["ErrorMessage"] = "Member Not found ";
                return RedirectToAction(nameof(Index));
            }
            ViewBag.MemberId = id; 

            return View();

        }


        [HttpPost] 
        public ActionResult DeleteConfirm (int id)
        {
            var result = memberService1.RemoveMember(id);

            if (result)
            {
                TempData["SuccessMessage"] = "Member Deleted Successfully";

            }
            else
            {

                TempData["ErrorMessage"] = "Delete member Failed";
            }


            return RedirectToAction(nameof(Index));


        }



        #endregion 












    }
}

GymManagementPL/Controllers/PlanController.cs
using GymManagmentBLL.Services.Interfaces;
using GymManagmentBLL.ViewModels.PlanViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GymManagementPL.Controllers
{
    public class PlanController : Controller
    {

        private readonly IPlanService planService1; 
        public PlanController(IPlanService planService )
        {
            planService1 = planService; 
        }


        public IActionResult Index()
        {
            var plans = planService1.GetAllPlans();

            return View(plans); 
        }


        public ActionResult Details (int id )
        {
            if (id <=0 )
            {
                TempData["ErrorMessage"] = "Plan id not found";
                return RedirectToAction(nameof(Index)); 
            }

            var plan = planService1.GetPlanDetails(id); 

            if (plan == null)
            {
                TempData["ErrorMessage"] = "Plan found";
                return RedirectToAction(nameof(Index));


            }

            return View(plan); 
        }



        public ActionResult Edit (int id )
        {
            if (id <= 0)
            {
                TempData["ErrorMessage"] = "Plan id not found";
                return RedirectToAction(nameof(Index));
            }

            var plan = planService1.GetPlantoUpdate(id);

            if (plan == null)
            {
                TempData["ErrorMessage"] = "Plan Not found";
                return RedirectToAction(nameof(Index));


            }

            return View(plan);
        }


        [HttpPost]
        public ActionResult Edit (int id ,UpdatePlanViewModel updatePlan   )
        {

            if (!ModelState.IsValid)
            {

                ModelState.AddModelError("WrongData", "Check data validation ");
                return View(nameof(Edit), updatePlan); 
               

            }

            var result = planService1.UpdatePlan(id, updatePlan); 
            if( result)
            {
                TempData["SuccessMessage"] = "Plan Updated";
            }
            else
            {
                TempData["ErrorMessage"] = "Plan Update failed";
            }
            return RedirectToAction(nameof(Index)); 
                  


        }


        [HttpPost]
        public ActionResult Activate (int id )
        {
            var result = planService1.Toogle(id); 

            if ( result)
            {
                TempData["SuccessMessage"] = "Plan status changed";

            }
            else
            {
                TempData["ErrorMessage"] = "Plan status failed";

            }

            return RedirectToAction(nameof(Index));



        }

       



    }




}

GymManagementPL/Controllers/SessionController.cs
using GymManagmentBLL.Services.Classes;
using GymManagmentBLL.Services.Interfaces;
using GymManagmentBLL.ViewModels.SesssionViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GymManagementPL.Controllers
{
    public class SessionController : Controller
    {

        private readonly ISessionService sessionService1;
        public SessionController(ISessionService sessionService)
        {
            sessionService1 = sessionService;
        }


        public IActionResult Index()
        {

            var sessions = sessionService1.GetAllSessions();
            return View(sessions);
        }



        public ActionResult Details(int id)

        {

            if (id <= 0)
            {
                TempData["ErrorMessage"] = "session id not found";
                return RedirectToAction(nameof(Index));
            }

            var session = sessionService1.GetSessionById(id);

            if (session == null)
            {
                TempData["ErrorMessage"] = "session not  found";
                return RedirectToAction(nameof(Index));

            }

            return View(session);


        }




        public ActionResult Create()
        {

            LoadtraniersDropDown();
            LoadDcatigoriesropDown();

            return View();
        }


        [HttpPost]
        public ActionResult Create(CreateSessionViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                LoadtraniersDropDown();
                LoadDcatigoriesropDown(); 
                return View(viewModel);
            }

            var result = sessionService1.CreateSession(viewModel);

            if (result)
            {
                TempData["SuccessMessage"] = "session Created Successfully";
            }
            else
            {
                TempData["ErrorMessage"] = "Add session Failed";
            }


            return RedirectToAction(nameof(Index));



        }


        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                TempData["ErrorMessage"] = "session id not found";
                return RedirectToAction(nameof(Index));
            }

            var session = sessionService1.GetSessionToUpdate(id);

            if (session == null)
            {
                TempData["ErrorMessage"] = "session Not found";
                return RedirectToAction(nameof(Index));

            }
            LoadtraniersDropDown(); 

            return View(session);

        }

        [HttpPost]
        public ActionResult Edit([FromRoute] int id, UpdateSessionViewModel viewModel)
        {

            if (!ModelState.IsValid)
            {
                LoadtraniersDropDown();
                
                return View(viewModel);
            }

            var result = sessionService1.UpdateSession(viewModel, id); 

            if(result)
            {
                TempData["SuccessMessage"] = "session updated Successfully";
            }
            else
            {
                TempData["ErrorMessage"] = "session Edit failed";

            }

            return RedirectToAction(nameof(Index)); 

        }

            

        public ActionResult Delete (int id )
        {

            if (id <= 0)
            {
                TempData["ErrorMessage"] = "session id not found";
                return RedirectToAction(nameof(Index));
            }

            var session = sessionService1.GetSessionById(id);

            if (session == null)
            {
                TempData["ErrorMessage"] = "session not  found";
                return RedirectToAction(nameof(Index));

            }
            ViewBag.Id = id; 
            return View();

        }


        [HttpPost]
        public ActionResult DeleteConfirmed(int id )
        {

            var result = sessionService1.RemoveSession(id); 

            if ( result )
            {



                TempData["SuccessMessage"] = "session Deleted Successfully";

            }
            else
            {

                TempData["ErrorMessage"] = "Delete session Failed";
            }


            return RedirectToAction(nameof(Index));

        }

        




       



        #region helper method  for create action  to load dropdown 


        private void LoadtraniersDropDown()
        {
            

            var trainers = sessionService1.GetTrainersfordropdown();
            ViewBag.trainers = new SelectList(trainers, "Id", "Name");
        }



        private void LoadDcatigoriesropDown()
        {
            var catigories = sessionService1.GetCategoeriesfordropdown();
            ViewBag.catigories = new SelectList(catigories, "Id", "Name");

           
        }

        #endregion







    }
}

GymManagementPL/Controllers/TrainerController.cs
using GymManagmentBLL.Services.Interfaces;
using GymManagmentBLL.ViewModels.TrainerViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GymManagementPL.Controllers
{
    public class TrainerController : Controller
    {

        private readonly ITrainerService _trainerService;

        public TrainerController(ITrainerService trainerService)
        {
            _trainerService = trainerService;
        }


        #region GetAll
        public ActionResult Index()
        {
            var trainers = _trainerService.GetAllTrainers();
            return View(trainers);
        }
        #endregion 



        #region GetDetails
        public ActionResult TrainerDetails(int id)
        {
            if (id <= 0)
            {
                TempData["ErrorMessage"] = "Id of Trainer Can't be 0 or Nigative Number";
                return RedirectToAction(nameof(Index));
            }

            var trainer = _trainerService.GetTrainerDetails(id);
            if (trainer is null)
            {
                TempData["ErrorMessage"] = "Trainer Not Found";
                return RedirectToAction(nameof(Index));
            }

            return View(trainer);
        }
        #endregion




        #region create



        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateTrainer(CreateTrainerViewModel createTrainer)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("DataInvaild", "Check Data and Missing Fields");
                return View(nameof(Create), createTrainer);
            }

            bool result = _trainerService.CreateTrainer(createTrainer);
            if (result)
                TempData["SuccessMessage"] = "Trainer Created Successfuly";
            else
                TempData["ErrorMessage"] = "Trainer Failed to Create, Check Phone and Email";

            return RedirectToAction(nameof(Index));
        }

        #endregion



        #region Edit

        public ActionResult TrainerEdit(int id)
        {
            if (id <= 0)
            {
                TempData["ErrorMessage"] = "Id of Trainer Can't be 0 or Nigative Number";
                return RedirectToAction(nameof(Index));
            }

            var trainer = _trainerService.GetTrainerToUpdate(id);
            if (trainer is null)
            {
                TempData["ErrorMessage"] = "Trainer Not Found";
                return RedirectToAction(nameof(Index));
            }

            return View(trainer);
        }
        [HttpPost]
        public ActionResult TrainerEdit([FromRoute] int id, TrianerToUpdateViewModel editTrainer)
        {
            if (!ModelState.IsValid)
                return View(editTrainer);

            var result = _trainerService.UpdateTrainer(id, editTrainer);
            if (result)
                TempData["SuccessMessage"] = "Trainer Updated Successfuly";
            else
                TempData["ErrorMessage"] = "Trainer Failed to Update, Check Phone and Email";

            return RedirectToAction(nameof(Index));
        }


        #endregion





        #region Delete


        public ActionResult Delete(int id)
        {
            if (id <= 0)
            {
                TempData["ErrorMessage"] = "Id of Trainer Can't be 0 or Nigative Number";
                return RedirectToAction(nameof(Index));
            }

            var trainer = _trainerService.GetTrainerDetails(id);
            if (trainer is null)
            {
                TempData["ErrorMessage"] = "Trainer Not Found";
                return RedirectToAction(nameof(Index));
            }

            ViewBag.TrainerId = id;

            return View();
        }
        [HttpPost]
        public ActionResult DeleteConfirm(int id)
        {
            var result = _trainerService.RemoveTrainer(id);

            if (result)
                TempData["SuccessMessage"] = "Trainer Deleted Successfuly";
            else
                TempData["ErrorMessage"] = "Trainer Failed to Delete";

            return RedirectToAction(nameof(Index));
        }


        #endregion




    }
}

GymManagementPL/Views/Shared/Alertview.cshtml
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const alertBox = document.getElementById("Alert");
        if (alertBox) {
            setTimeout(() => {
                alertBox.style.transition = "opacity 0.5s ease";
                alertBox.style.opacity = "0";
                setTimeout(() => alertBox.remove(), 500);
            }, 1500);
        }
    });
</script>

GymManagementPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="../images/icon.svg" type="image/x-icon" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Thambi+2:wght@400..800&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" />
    <!-- ^ Bootstrap 5.3.8 css file -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- ^ Our main css file -->
    <link rel="stylesheet" href="~/css/style.css" />
    <title>Power fitness | Home</title>
</head>


<body>

    <header>
        <!-- ^ navbar -->
        <nav class="navbar navbar-expand-lg bg-white my-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.jpg" alt="" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav m-auto mb-2 mb-lg-0 mt-3 mt-lg-0">
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link active px-3 py-2 mx-2 fw-bolder fs-5" aria-current="page"
                               asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-3 py-2 mx-2 fw-bolder fs-5" aria-current="page"  asp-controller="Member"   asp-action="Index"> Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  px-3 py-2 mx-2 fw-bolder fs-5" aria-current="page"  asp-controller="Trainer" asp-action="Index">Trainers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  px-3 py-2 mx-2 fw-bolder fs-5" aria-current="page"  asp-controller="Session" asp-action="Index">Sessions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  px-3 py-2 mx-2 fw-bolder fs-5" aria-current="page"  asp-controller="Plan" asp-action="Index">Plans</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  px-3 py-2 mx-2 fw-bolder fs-5" aria-current="page"
                               href="#">Memberships</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  px-3 py-2 mx-2 fw-bolder fs-5" aria-current="page" href="#">
                                Sessions
                                Schedule
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>